export const INTERESTS = [
  { id: 'music',       label: '🎵 Music' },
  { id: 'travel',      label: '✈️ Travel' },
  { id: 'fitness',     label: '💪 Fitness' },
  { id: 'food',        label: '🍳 Cooking' },
  { id: 'gaming',      label: '🎮 Gaming' },
  { id: 'art',         label: '🎨 Art' },
  { id: 'reading',     label: '📚 Reading' },
  { id: 'film',        label: '🎬 Film' },
  { id: 'nature',      label: '🌿 Nature' },
  { id: 'pets',        label: '🐾 Pets' },
  { id: 'sports',      label: '🏅 Sports' },
  { id: 'dancing',     label: '💃 Dancing' },
  { id: 'photography', label: '📸 Photography' },
  { id: 'fashion',     label: '👗 Fashion' },
  { id: 'tech',        label: '💻 Tech' },
  { id: 'yoga',        label: '🧘 Yoga' },
  { id: 'coffee',      label: '☕ Coffee' },
  { id: 'wine',        label: '🍷 Wine' },
  { id: 'hiking',      label: '🥾 Hiking' },
  { id: 'astrology',   label: '♈ Astrology' },
  { id: 'faith',       label: '🙏 Spirituality' },
  { id: 'activism',    label: '✊ Activism' },
  { id: 'comedy',      label: '😂 Comedy' },
  { id: 'theatre',     label: '🎭 Theatre' },
];
